---
- name: check if it is installed
  ansible.windows.win_service_info:
    name: IPBan
  register: ipban_service

- name: uninstall if installed
  when: ipban_service.exists
  block:
    - name: stop service
      win_service:
        name: IPBan
        state: stopped
    
    - name: remove service
      win_service:
        name: IPBan
        state: absent

    - name: create temp directory to current state
      win_tempfile:
        suffix: ipban
        state: directory
      register: ipban_temp_dir

    - name: copy config and db files to temp directory
      win_copy:
        src: "{{ ipban_app_dir }}\\{{ item }}"
        dest: "{{ ipban_temp_dir.path }}\\{{ item }}"
        remote_src: yes
      loop:
        - ipban.config
        - ipban.override.config
        - ipban.sqlite
        - nlog.config

    - name: delete app folder
      win_file:
        path: "{{ ipban_app_dir }}"
        state: absent

- name: ensure exists app dir
  win_file:
    path: "{{ ipban_app_dir }}\\"
    state: directory

- name: "download ipban {{ ipban_version }}"
  win_get_url:
    url: "https://github.com/DigitalRuby/IPBan/releases/download/{{ ipban_version }}/IPBan-Windows-x64_{{ ipban_version | replace('.', '_') }}.zip"
    dest: "{{ ipban_app_dir }}\\"
  tags:
    - ipban_install

- name: extract and cleanup
  win_unzip:
    src: "{{ ipban_app_dir }}\\IPBan-Windows-x64_{{ ipban_version | replace('.', '_') }}.zip"
    dest: "{{ ipban_app_dir }}"
    recuse: yes
    delete_archive: yes
  tags:
    - ipban_install
  
- name: copy back over the config and db files
  win_copy:
    src: "{{ ipban_temp_dir.path }}\\{{ item }}"
    dest: "{{ ipban_app_dir }}\\{{ item }}"
    remote_src: yes
  when: ipban_service.exists
  tags:
    - ipban_install
  loop:
    - ipban.config
    - ipban.override.config
    - ipban.sqlite
    - nlog.config

- name: ensure temp dir is not exists
  win_file:
    path: "{{ ipban_temp_dir.path }}"
    state: absent
  when: ipban_service.exists
  tags:
    - ipban_install

- name: ensure audit policy is logging
  win_command: "auditpol.exe /set /category:\"{{ item }}\" /success:enable /failure:enable"
  loop:
    - "{69979849-797A-11D9-BED3-505054503030}"
    - "{69979850-797A-11D9-BED3-505054503030}"
  tags:
    - ipban_install
    - ipban_configure

- name: create service
  win_service:
    name: IPBan
    path: "{{ ipban_app_dir }}\\DigitalRuby.IPBan.exe"
    display_name: IPBan
    start_mode: delayed
    type: win32_own_process
    state: started
    description: "Automatically builds firewall rules for abusive login attempts: https://github.com/DigitalRuby/IPBan"
    failure_actions:
      - type: restart
        delay_ms: 60000
      - type: restart
        delay_ms: 60000
      - type: restart
        delay_ms: 60000
    failure_reset_period_sec: 9999
  tags:
    - ipban_install
    - ipban_configure
    - ipban_run

- name: config ipban
  win_template:
    src: ipban.config.j2
    dest: "{{ ipban_app_dir }}\\ipban.config"
  tags:
    - ipban_configure
