---
name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible-core

      - name: Create ansible.cfg to test role
        run: printf '[defaults]\nroles_path=../' >ansible.cfg

      - name: Role syntax check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
